### ISSUE TITLE
release buildx failed with: ERROR on nightly

### ISSUE THREAD

**Issue by jensens** [plone/plone-frontend#17]
```
release buildx failed with: ERROR: failed to solve: process "/bin/sh -c cd plone-frontend && yarn install && yarn build" did not complete successfully: exit code: 1
```
see https://github.com/plone/plone-frontend/actions/runs/3139388511

@ericof @sneridagh I have no idea why. This has to get fixed.

**Comment by sneridagh** [comment]
I know what it is. I'll take a look.

**Comment by jensens** [comment]
Thanks @sneridagh - after your fixes it runs again.
