### ISSUE TITLE
Volto 15 Nightly fails

### ISSUE THREAD

**Issue by jensens** [plone/plone-frontend#24]
https://github.com/plone/plone-frontend/actions/runs/3277346001/jobs/5394506611

ping @sneridagh 

Any idea why?

**Comment by davisagli** [comment]
@jensens That looks like a network glitch between Github and npm. I just started a rerun.

**Comment by stevepiercy** [comment]
We just had [someone report that there is still an issue with the 15.16 release](https://github.com/plone/documentation/issues/1335#issuecomment-1285759843). It looks like its tag was still not pushed to Docker Hub: https://hub.docker.com/r/plone/plone-frontend/tags

**Comment by sneridagh** [comment]
I have no clue what's going on, it seems indeed that there are network errors here and there at some point at the build. I checked out and the resources are there...

`#17 595.0 error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-7.5.6.tgz: ESOCKETTIMEDOUT".`

**Comment by jensens** [comment]
Is there some rate limit on registry.yarnpkg.com?

**Comment by davisagli** [comment]
I [increased the network timeout](https://github.com/plone/plone-frontend/commit/6437619c25436d23611dbb5757a2598c0cc285cd) and it [eventually finished](https://github.com/plone/plone-frontend/actions/runs/3309059126/jobs/5461874828) -- but it took 3 hours. It appears to be building the arm64 image that is very slow for some reason.

**Comment by sneridagh** [comment]
It normally took 3 times more (like 45mins), expected due to the emulation, but not 3 hours. :(

**Comment by sneridagh** [comment]
I investigated a bit:

https://dan-jenkins.co.uk/enabling-native-arm64-builds-with-github-actions/

outdated since now setup-buildx-action supports it:
https://github.com/docker/setup-buildx-action/blob/master/docs/advanced/append-nodes.md

Maybe we can investigate this a bit further...

**Comment by sneridagh** [comment]
They are green again, but the build now takes almost 3h :(
