### ISSUE TITLE
Use @plone/generator-volto

### ISSUE THREAD

**Issue by avoinea** [plone/plone-frontend#4]
https://github.com/plone/plone-frontend/blob/56df8fa812a4bf22cc7baddb711f14aac10af54e/14/14.0.0-alpha/Dockerfile.node14#L19

We should have only one source of truth and use [@plone/generator-volto](https://github.com/plone/volto/tree/master/packages/generator-volto) to generate Volto project within this image instead of having to maintain it in multiple places.

**Comment by ericof** [comment]
Good point, taking care of it
