### ISSUE TITLE
What should we do with nightly and nightly17 images?

### ISSUE THREAD

**Issue by fredvd** [plone/plone-frontend#40]
@sneridagh Now that 17 is officially out and latest, nightly17 doesn't make much sense anymore. 

Also: the nighty buildling of these images takes up quite some resources. Where are these nightly's used again?  I remember they migth be used for some integration testing in plone/volto?  

If so, we should at least look at removing older nightlyies after a while, because I think they are now stacking up on ghcr.io.

**Comment by davisagli** [comment]
> I remember they migth be used for some integration testing in plone/volto?

There's no mention of them anywhere in the plone org except here: https://github.com/search?q=org%3Aplone%20nightly17&type=code

> If so, we should at least look at removing older nightlyies after a while, because I think they are now stacking up on ghcr.io.

Even if there is a reason to still build them, I'm not sure there is a reason to keep them for more than a few days.

**Comment by sneridagh** [comment]
@fredvd I can't remember who or why the nightlies are in place. I guess that it was because plone-backend has them initially. We never used them in the CI or anywhere. Someone said that it might be handy to have. Personally, I also never used them. Having them around could be useful, but of course maintaining them for a week or so? Is that possible?

**Comment by davisagli** [comment]
My 2 cents: if no one is using them, then remove them, rather than spend effort to maintain them and automatically clean them up.

Maybe @ericof has opinions here?

**Comment by stevepiercy** [comment]
FWIW, there is only one nightly mentioned in the docs, and that is for Classic UI v6, but I don't know whether that is accurate.

https://6.docs.plone.org/install/index.html?highlight=nightly

Whatever you decide, I would suggest posting to Community with the decision with whatever lead time you think is best, just in case someone not paying attention to GitHub notifications misses this and cares about it.

**Comment by mauritsvanrees** [comment]
I don't use this nightly.  For me it is fine to disable the job.
Could be useful to keep the job definition and related code around though.

**Comment by davisagli** [comment]
It was agreed in the volto meeting to disable them.

done for the 16.x branch in https://github.com/plone/plone-frontend/commit/a484a1b33cbb1797997ec8c383f49fb960dde23b and 17.x branch in https://github.com/plone/plone-frontend/commit/fe852252ffbc7bf04e714fe00c6b84ba24e93ae1

@fredvd @sneridagh  FYI I just switched the 17.x branch to be the default branch. This probably changes where github looks for the GHA workflow definititions. Let me know if you see any unintended consequences.
