### ISSUE TITLE
Needs to have deb package `make` installed

### ISSUE THREAD

**Issue by tiberiuichim** [plone/plone-frontend#41]
https://github.com/plone/plone-frontend/blob/1791a24f6d9d5efadc76571ccc0bfd7c88d0c16d/Dockerfile.prod#L14C4-L14C56

Because in second stage, we do `yarn install` and then this wants to get executed as a postinstall script to `@plone/volto`:

https://github.com/plone/volto/blob/6520d8ed8a8e077652db30ffd186e34fb5be2c79/package.json#L36

**Comment by davisagli** [comment]
@tiberiuichim Can you show where you are seeing an error from this? I looked in https://github.com/plone/plone-frontend/actions/runs/6665911411 but didn't find it.

From what I can see, `yarn install` is run in the builder image (https://github.com/plone/plone-frontend/blob/17.x/Dockerfile.builder#L34) and that already has `make` as a dependency of `build-essential` (https://github.com/plone/plone-frontend/blob/17.x/Dockerfile.builder#L13).

The final Dockerfile just copies files from the prod-config image without running anything.

**Comment by tiberiuichim** [comment]
@davisagli My colleague was using an depending on an older version of plone-frontend in his Dockerfile, it was solved when we've upgraded to the latest version.
