### ISSUE TITLE
18.x Dockerfiles

### ISSUE THREAD

**Issue by avoinea** [plone/plone-frontend#53]
Can't find the Dockerfiles for 18.x and the links in README are also broken. Same on Dockerhub https://hub.docker.com/r/plone/plone-frontend

**Comment by davisagli** [comment]
@avoinea For 18 we currently have two sets of Dockerfiles:
1. with pnpm: https://github.com/plone/plone-frontend/tree/18.x/pnpm
2. with yarn: https://github.com/plone/plone-frontend/tree/18.x/yarn

Good point that the readme needs to be updated.

**Comment by davisagli** [comment]
@avoinea Thanks, fixed in https://github.com/plone/plone-frontend/commit/b087bb61b226754e292cc1b201485eb26d66ced7
